import { InfoChip } from '@/components/ui/info-chip';
import { SectionHeader } from '@/components/ui/section-header';
import { SelectFilter } from '@/components/ui/select-filter';
import { getReportingVersions } from '@/lib/data/versions/get-reporting-versions';

export const dynamic = 'force-dynamic';

type AdminPreReadPageProps = {
  searchParams: Promise<{
    version?: string;
    reportversion?: string;
  }>;
};

function formatMonth(value: string) {
  const date = new Date(`${value}T00:00:00`);
  if (Number.isNaN(date.getTime())) return value;
  return new Intl.DateTimeFormat('en-US', { month: 'long', year: 'numeric' }).format(date);
}

export default async function AdminPreReadPage({ searchParams }: AdminPreReadPageProps) {
  const params = await searchParams;
  const requestedVersion = params.version ?? params.reportversion;
  const versions = await getReportingVersions();
  const selected =
    versions.find((item) => item.reportingVersionId === requestedVersion) ?? versions[0];

  if (!selected) {
    return (
      <section className="space-y-6">
        <div className="rounded-3xl border border-slate-200 bg-white p-8 shadow-sm">
          <p className="text-sm font-medium uppercase tracking-[0.18em] text-slate-500">Admin</p>
          <h1 className="mt-3 text-3xl font-semibold tracking-tight text-slate-900">Pre-Read PDF</h1>
          <p className="mt-3 text-sm leading-6 text-slate-600">No reporting versions found.</p>
        </div>
      </section>
    );
  }

  const pdfSrc = `/api/admin/preread/pdf?version=${encodeURIComponent(selected.reportingVersionId)}`;

  return (
    <section className="space-y-6">
      <SectionHeader
        eyebrow="Admin"
        title="Pre-Read PDF Preview"
        description="Preview of the executive pre-read paper generated by section."
        actions={
          <>
            <InfoChip label="Period" value={formatMonth(selected.periodMonth)} />
            <InfoChip label="Version" value={selected.versionName} />
            <SelectFilter
              paramName="version"
              label="Change version"
              value={selected.reportingVersionId}
              options={versions.map((version) => ({
                value: version.reportingVersionId,
                label: `${version.periodMonth} - ${version.versionName}`,
              }))}
            />
          </>
        }
      />

      <article className="rounded-[18px] border border-slate-200 bg-white p-3">
        <div className="mb-3 flex justify-end">
          <a
            href={pdfSrc}
            target="_blank"
            rel="noreferrer"
            className="rounded-full border border-slate-300 bg-white px-4 py-2 text-xs font-semibold uppercase tracking-[0.12em] text-slate-700 hover:border-slate-400"
          >
            Open PDF in New Tab
          </a>
        </div>
        <iframe
          title="Pre-Read PDF Preview"
          src={pdfSrc}
          className="h-[78vh] w-full rounded-[12px] border border-slate-200"
        />
      </article>
    </section>
  );
}
