CREATE TABLE IF NOT EXISTS `chiesi-committee.chiesi_committee_stg.stg_commercial_operations_ar_aging` (
  upload_id STRING,
  row_number INT64,
  account STRING,
  customer STRING,
  document_number STRING,
  document_date DATE,
  invoice_amount NUMERIC,
  reference STRING,
  invoice_due_date DATE,
  payment_group STRING,
  days_past_due NUMERIC,
  assignment STRING,
  channel_group STRING,
  status STRING,
  aging_group STRING,
  channel STRING,
  billing_year INT64,
  customer_groups STRING,
  management STRING,
  source_payload_json JSON,
  normalized_at TIMESTAMP
);

CREATE TABLE IF NOT EXISTS `chiesi-committee.chiesi_committee_stg.stg_commercial_operations_ar_collection` (
  upload_id STRING,
  row_number INT64,
  source_type STRING,
  account STRING,
  customer STRING,
  invoice_reference STRING,
  assignment STRING,
  reference STRING,
  document_number STRING,
  document_date DATE,
  payment_date DATE,
  terms_of_payment STRING,
  document_type STRING,
  invoice_amount NUMERIC,
  period_month DATE,
  customer_reference STRING,
  clearing_document STRING,
  net_due_date DATE,
  channel_group STRING,
  text STRING,
  document_header_text STRING,
  fiscal_year INT64,
  source_payload_json JSON,
  normalized_at TIMESTAMP
);
