-- Business Excellence Field Force serving layer
-- Run in BigQuery (Standard SQL)
-- Project: chiesi-committee
-- Region: EU
--
-- The application refresh implementation lives in:
-- lib/serving/refresh-business-excellence-field-force.ts
--
-- Objects created by the refresh:
-- 1) chiesi_committee_serving.vw_business_excellence_ff_t1_medical_universe
-- 2) chiesi_committee_serving.vw_business_excellence_ff_t2_interactions_matched
-- 3) chiesi_committee_serving.vw_business_excellence_ff_t3_effective_days
-- 4) chiesi_committee_serving.business_excellence_ff_hcp_month
-- 5) chiesi_committee_serving.business_excellence_ff_hcp_channel_month

CREATE SCHEMA IF NOT EXISTS `chiesi-committee.chiesi_committee_serving`
OPTIONS (
  location = 'EU',
  description = 'Serving dataset for Next.js and BI application-ready views'
);

-- T1: filtered, normalized medical universe.
CREATE OR REPLACE VIEW `chiesi-committee.chiesi_committee_serving.vw_business_excellence_ff_t1_medical_universe` AS
WITH upload_scope AS (
  SELECT
    upload_id,
    reporting_version_id,
    LOWER(TRIM(module_code)) AS module_code,
    source_as_of_month,
    period_month,
    uploaded_at
  FROM `chiesi-committee.chiesi_committee_raw.uploads`
  WHERE status IN ('normalized', 'published')
),
latest_medical_upload AS (
  SELECT upload_id, reporting_version_id
  FROM upload_scope
  WHERE module_code IN (
    'business_excellence_salesforce_fichero_medico',
    'business_excellence_fichero_medico',
    'fichero_medico'
  )
  QUALIFY ROW_NUMBER() OVER (
    PARTITION BY reporting_version_id
    ORDER BY COALESCE(source_as_of_month, period_month) DESC, uploaded_at DESC
  ) = 1
)
SELECT
  lu.reporting_version_id,
  m.upload_id,
  m.period_month,
  LOWER(TRIM(m.bu)) AS bu,
  NULLIF(TRIM(m.district), '') AS district,
  NULLIF(TRIM(m.territory), '') AS territory_name,
  UPPER(COALESCE(NULLIF(TRIM(m.territory_normalized), ''), REGEXP_REPLACE(TRIM(COALESCE(m.territory, '')), r'[^a-zA-Z0-9]+', ''))) AS territory_normalized,
  COALESCE(NULLIF(TRIM(m.potencial), ''), 'N/A') AS potencial,
  COALESCE(NULLIF(TRIM(m.specialty_consolidated), ''), 'N/A') AS specialty_consolidated,
  NULLIF(TRIM(m.full_name), '') AS client_name,
  UPPER(REGEXP_REPLACE(TRIM(COALESCE(NULLIF(m.onekey_id, ''), NULLIF(m.ims_id, ''))), r'[^a-zA-Z0-9]+', '')) AS doctor_key,
  UPPER(REGEXP_REPLACE(TRIM(COALESCE(m.onekey_id, '')), r'[^a-zA-Z0-9]+', '')) AS onekey_key,
  UPPER(REGEXP_REPLACE(TRIM(COALESCE(m.ims_id, '')), r'[^a-zA-Z0-9]+', '')) AS ims_key,
  SAFE_CAST(m.objetivo AS NUMERIC) AS objective,
  JSON_VALUE(m.source_payload_json, '$."Account Type"') AS account_type,
  m.normalized_at
FROM `chiesi-committee.chiesi_committee_stg.stg_business_excellence_salesforce_medical_file` m
JOIN latest_medical_upload lu
  ON lu.upload_id = m.upload_id
WHERE LOWER(TRIM(m.bu)) IN ('air', 'care')
  AND SAFE_CAST(m.objetivo AS NUMERIC) > 0
  AND COALESCE(NULLIF(TRIM(m.onekey_id), ''), NULLIF(TRIM(m.ims_id), '')) IS NOT NULL
  AND JSON_VALUE(m.source_payload_json, '$."Account Type"') IN (
    'MP (Medical Professional)_BR',
    'MP (Medical Professional) MX',
    'Private Practice MX'
  );

-- T2/T3 and mart tables are generated by the TypeScript refresh function to avoid
-- duplicating a long implementation in two places. Keep this file as the object
-- contract and run the app refresh after Salesforce uploads are published.
